### ISSUE TITLE
Avatar covering scrollbar.

### ISSUE THREAD

**Issue by ptychu** [wizdmio/wizdm#10]
Hi :)

I've noticed that in narrow windows avatar picture may cover scroll bar:
![image](https://user-images.githubusercontent.com/54937876/79462374-af204a00-7ff7-11ea-8be2-45a9e43abb3d.png)

It also makes the navbar cover the scroll bar after a scroll:
![image](https://user-images.githubusercontent.com/54937876/79462595-01616b00-7ff8-11ea-8f6b-9844c3d89340.png)

I have two ideas for a fix and I can provide a pull request, but I wanted to hear your opinion first.

1. Add `position: sticky` and `height: fit-content` to `<header>` element. Result is on the pictures below:
![image](https://user-images.githubusercontent.com/54937876/79463141-bd229a80-7ff8-11ea-8df9-c28ecf8acaef.png)
![image](https://user-images.githubusercontent.com/54937876/79463169-c7dd2f80-7ff8-11ea-95d3-9a5411b903d1.png)

2. Move scrollable area into `<mat-sidenav-content>` element. 
Although I feel like it looks a bit cleaner it needs more attention, as it may impact how animations work. It also has immediate side-effect of breaking the navbar shadow:

![image](https://user-images.githubusercontent.com/54937876/79463982-d24bf900-7ff9-11ea-9986-50b5e90d80e3.png)
![image](https://user-images.githubusercontent.com/54937876/79464005-d7a94380-7ff9-11ea-8c1c-529b03b8c951.png)

Which approach would you consider to be better? Do you have any tips on how to proceed? I'd love to contribute to the project!

Tested on commit 283021202639c1dec7bb35aa657444b064287806
Window width for pictures: 786px
Tested on browsers: 
Chrome: 80.0.3987.122
Firefox: 74.0.1

**Comment by ptychu** [comment]
https://wizdm.io seems to be a bit out of date, but current state behaves like my 1st solution.

**Comment by lasfrancisco** [comment]
Hi there, thank you for your proposals. Can you tell me a bit more about how to reproduce the issue? I never noticed this issue using chrome on both win and mac so I wonder which browser you experienced this issue with.

**Comment by lasfrancisco** [comment]
Besides, I switched between using the main window (like this very last version) and an inner element as the main scrolling container several times but there are too many side effects to pick one as the perfect solution.

**Comment by lasfrancisco** [comment]
It seems what you describe was caused by using a div inside the navigator as the main scrolling container. I believe we got back to normal by reverting back to the main window. Please confirm.

**Comment by ptychu** [comment]
Hi @lasfrancisco,

I confirm that issue doesn't reproduce anymore. We can close this issue, as well as my PR ;)

Tested on:
Commit 410c8976051798bb78a7abd3d3d0fd6174c56276
Browsers:
- Linux Chrome: 81.0.4044.122
- Linux Firefox 75.0 (64-bit)

Previous tests were executed on windows and on linux machines. Issue reproduced in every case. Here are some details for reference:
Commit 2830212
Window width for pictures: 786px
Tested on browsers:
- Windows Chrome: 80.0.3987.122
- Windows Firefox: 74.0.1
- Linux Chrome: 81.0.4044.122
- Linux Firefox 75.0 (64-bit)
