### ISSUE TITLE
Publish this animations library as a separate project ...

### ISSUE THREAD

**Issue by kolkov** [wizdmio/wizdm#15]
I am sure that this library deserves to be published on [npmjs.com](https://npmjs.com)  separately from this wonderful starter.  Are you planning to do this?  I think she would have been a great success!
https://github.com/wizdmio/wizdm/tree/master/libs/animate

I think you may use some ideas for publishing from my library.
https://github.com/kolkov/angular-editor
If you do not have such plans for the near future, then I can publish it with reference to this project and your authorship.

Thanks for your grate work!

**Comment by lasfrancisco** [comment]
Hi, thank you for your feedback. I'll surely look into your repo. Besides, [@wizdm/animate](https://www.npmjs.com/package/@wizdm/animate) is already a library available on npm. I'll be releasing few other packages as soon as the corresponding documentation is ready and available on wizdm.io.

**Comment by kolkov** [comment]
Thanks for the quick reply, I searched for a long time, but could not find it.)
