### ISSUE TITLE
TypeScript Error: 3.9.2 is been installed instead of 3.8.3

### ISSUE THREAD

**Issue by paulayo93** [wizdmio/wizdm#16]
**### TypeScript Error**
I ran into this issue after completing the necessary requirement to set up the application and start running.  Using the "npm start" or "ng serve" reproduces the same result.

![Annotation 2020-05-18 173421](https://user-images.githubusercontent.com/52790286/82253351-bb762a80-9948-11ea-91b3-f04db7fee6d2.png)

![typeversion](https://user-images.githubusercontent.com/52790286/82253899-c7162100-9949-11ea-8107-0f1fdebcc4b4.png)

**### Attempt to Resolve Bug**

I uninstalled the current typescript package and installed it with the command "npm install --save-dev typescript@^3.8.3". What I got in my package.json was typescript@3.9.2

Please If need be for more information on the behaviour of this bug I will be ready to provide. 

How can I resolve this issue? 

**Thanks**

**Comment by lasfrancisco** [comment]
Hi Paul, thanks for the feedback. There's was a little mistake in the [package.json](https://github.com/wizdmio/wizdm/blob/master/package.json#L87). 
I took the opportunity to drop the core-js dependency, since es6 polyfills are managed by the cli according to the browserlist (as of v8) while building the differential bundles.

**Comment by lasfrancisco** [comment]
Still issues while compiling a fresh clone.

**Comment by lasfrancisco** [comment]
Fixed for clean builds upgrading to ng9.1.7.

**Comment by paulayo93** [comment]
Hi @lasfrancisco 
currently having issues with loading  the page in the browser:

**localhost didn’t send any data.**


![browsererror](https://user-images.githubusercontent.com/52790286/82332814-c7f89280-99dd-11ea-8852-af3e6e6398d5.png)

The project compiled successfully but the above error appears in the browser.
I am on a window machine 10 Pro
Version:  1909
OS Build: 1836.778

Any Suggestion for a fix

**Comment by lasfrancisco** [comment]
Make sure listening to the http**s**://localhost:4200. If you're using vscode you'll get the tools already setup to run chrome in debug mode on https by default. Be sure to install the ssl certificate you find in the wizdm/ssl folder on your platform.

**Comment by paulayo93** [comment]
Finally running on my machine

Thanks a lot!
