### ISSUE TITLE
Animate not work in safari

### ISSUE THREAD

**Issue by Garudkar-Dnyaneshwar** [wizdmio/wizdm#34]
wizdm animate not work as expected in safari (desktop version). Some glitches observe.
Thanks for this amazing repo :)

**Comment by paulayo93** [comment]
Thanks for letting us know this.

@Garudkar-Dnyaneshwar Can you be more detailed about the issues you observed?

Some screenshots/gifs would help greatly.

Thanks a lot

**Comment by lasfrancisco** [comment]
Can’t reproduce the problem, please check the latest version.
