### ISSUE TITLE
"npm install @wizdm/stripe" not working with Angular 11

### ISSUE THREAD

**Issue by leiomokusei** [wizdmio/wizdm#38]
### Affected package
The issue is caused by @wizdm/stripe package.

### Describe the bug
When running "npm install @wizdm/stripe" I have:

```
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/cdk@"^10.0.0" from @wizdm/stripe@2.0.0
npm ERR! node_modules/@wizdm/stripe
npm ERR!   @wizdm/stripe@"*" from the root project

```
### Is this a regression?
I don't know

### Expected behavior
It should install

### Environment
 - wizdm version
 - Device: Desktop
 - OS: Mac
- Using npm@7.0.14
- Using node@v15.3.0

**Comment by lasfrancisco** [comment]
The **@wizdm/stripe** package works with ng10 and expects @angular/cdk and @angular/material to be there. 
We'll be releasing packages for ng11 once the project will be migrated to the latest version while I'm afraid legacy versions before v10 won't be supported. 
If you're using an older version I can guide you through the use of the package source codes in your own app, eventually.
Would you please confirm the version of Angular you're using?

**Comment by leiomokusei** [comment]
Using ng11

**Comment by ptychu** [comment]
@leiomokusei: TLDR: Use node 14 and npm 6. 

You may be facing problems with angular not being compatible with node 15. It's not officially supported - [Angular requires latest LTS version of node](https://angular.io/guide/setup-local). If you're interested in more details you can look at https://github.com/angular/angular-cli/issues/19957 or https://github.com/angular/angular-cli/issues/19470

**Comment by lasfrancisco** [comment]
Hi there, the latest version of the package does now support ng11.
