### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by cbawebdesign** [wizdmio/wizdm#42]
hello, this is not a bug I am just really confused on where to change the logo .  I switched the wmlogo.png and .svg to my desired logos (kept same name) and nothing happened. 

Is there somewhere else I need to change the logo in the code? thanks!

**Comment by lasfrancisco** [comment]
Hi there, there's no need of keeping the same name, actually, but if you want to customize the logo you have to add a "logo" section in the navigator.json file under assets/i18n/en such as:

...
    "title": "Wizdm - Get your app done right",
    "description": "The fully featured boilerplate to launch your web application quickly",
     "logo": {
          "url": assets/img/mylogo.png
     }
...

You can also adjust the size in pixel (default is 56). See here: https://github.com/wizdmio/wizdm/blob/master/wizdm/src/app/navigator/navigator.component.html#L23
