### ISSUE TITLE
Errors in serve / build

### ISSUE THREAD

**Issue by mtabaj** [wizdmio/wizdm#6]
I guess you're working on the project, but by now it doesn't build.  I've didn't change anything.

ERROR in apps/wizdm/src/app/core/project/project-wrapper.ts(35,31): error TS2554: Expected 2 arguments, but got 3.
apps/wizdm/src/app/core/project/project-wrapper.ts(65,10): error TS2540: Cannot assign to 'id' because it is a read-only property.
apps/wizdm/src/app/core/project/project-wrapper.ts(108,47): error TS2554: Expected 1 arguments, but got 2.
apps/wizdm/src/app/core/project/project-wrapper.ts(132,8): error TS2339: Property 'pipe' does not exist on type 'Promise<wmProject>'.
apps/wizdm/src/app/core/project/project-wrapper.ts(133,26): error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'wmProject'.
  Type '{}' is missing the following properties from type 'wmProject': name, author, type
apps/wizdm/src/app/core/project/project.service.ts(12,15): error TS2345: Argument of type '"/projects"' is not assignable to parameter of type 'CollectionReference'.
apps/wizdm/src/app/core/project/project.service.ts(55,36): error TS2339: Property 'toPromise' does not exist on type 'Promise<wmProject>'.
apps/wizdm/src/app/pages/user-info/user-info.component.ts(21,61): error TS2554: Expected 1 arguments, but got 2.
libs/connect/src/lib/uploader/uploader.service.ts(24,15): error TS2345: Argument of type '""' is not assignable to parameter of type 'CollectionReference'.
libs/connect/src/lib/uploader/uploader.service.ts(33,10): error TS2540: Cannot assign to 'path' because it is a read-only property.
libs/connect/src/lib/uploader/uploader.service.ts(45,8): error TS2339: Property 'toPromise' does not exist on type 'Promise<wmFile[]>'.
libs/connect/src/lib/uploader/uploader.service.ts(143,22): error TS2339: Property 'toPromise' does not exist on type 'Promise<wmFile>'.
libs/connect/src/lib/user/user-profile.service.ts(33,25): error TS2554: Expected 2 arguments, but got 3.
libs/connect/src/lib/user/user-profile.service.ts(89,14): error TS2540: Cannot assign to 'id' because it is a read-only property.

**Comment by lasfrancisco** [comment]
Sorry for that. I believe now it builds correctly
